### ISSUE TITLE
Stripe issue

### ISSUE THREAD

**Issue by Charlio99** [giridhar7632/funto-storefront#1]
Hello!

I love your storefront, I'm testing it to use it as a base template for my small store, I've been trying to enable Stripe, but I'm getting an error after payment is done.
I'm using Stripe local development

This is the error I'm getting:
````
page: '/order/confirmed/[id]'
}
  43 |     exp_year: number
  44 |     exp_month: number
> 45 |   } = (payment.data.charges as any).data[0].payment_method_details.card
     |                                    ^
  46 |
  47 |   return (
  48 |     <div className="text-base-regular flex flex-col">
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 178 ms (1734 modules)
error - src/modules/order/components/payment-details/index.tsx (45:36) @ StripeDetails
error - TypeError: Cannot read properties of undefined (reading 'data')
    at StripeDetails (webpack-internal:///./src/modules/order/components/payment-details/index.tsx:86:39)
````

**Comment by giridhar7632** [comment]
Hey @Charlio99 

Can you share your development environment details? This storefront is built based on the Medusa backend starter. You have to enable the stripe payments at the backend project. I believe I can help fix the error if you can share the complete project structure.

By seeing your error, I can't say the exact fix but I think there is no response coming from the backend of the project.

**Comment by Charlio99** [comment]
> Hey @Charlio99
> 
> Can you share your development environment details? This storefront is built based on the Medusa backend starter. You have to enable the stripe payments at the backend project. I believe I can help fix the error if you can share the complete project structure.
> 
> By seeing your error, I can't say the exact fix but I think there is no response coming from the backend of the project.

Thanks for the fast reply @giridhar7632 

I created a medusa backend, funto frontend and medusa admin, they only thing I did is enabling stripe (enabling it on the backend and adding env to funto storefront). The thing it fails it's after the order when you are redirected to the order details and when in your account click order details for an order. I didn't do any further changes.

**Comment by Charlio99** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/7070420/208553139-5502144a-5e3b-4e48-8964-38fec6445953.png">
